# docker-compose.yml

version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8002
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    ports:
      - "8005:8002"
    env_file:
      - .envs/.env.dev
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  postgres_data:
  static_volume: